name: Daily Digest verifier

on:
  # schedule:
  #   - cron: '30 4 * * *'

# Job 
jobs:
  run-script:
    runs-on: ubuntu-latest

    # Steps
    steps:
    - uses: actions/checkout@v3

    - name: Execute Daily_digest_verifier.sh
      run: |
        chmod +x ./Daily_digest_verifier.sh
        ./Daily_digest_verifier.sh
